import { LABELS_CONSTANTS as LABELS } from './labels.constants';
import { APP_ROUTES as ROUTES } from '@app/app.routes';

export const LABELS_MAPPING = {
  [ROUTES.CHAPTER_1_SCENE_1]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_1,
  [ROUTES.CHAPTER_1_SCENE_2]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_2,
  [ROUTES.CHAPTER_1_SCENE_3]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_3,
  [ROUTES.CHAPTER_1_SCENE_4]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_4,
  [ROUTES.CHAPTER_1_SCENE_5]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_5,
  [ROUTES.CHAPTER_1_SCENE_6]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_6,
  [ROUTES.CHAPTER_1_SCENE_7]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_7,
  [ROUTES.CHAPTER_1_SCENE_8]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_8,
  [ROUTES.CHAPTER_1_SCENE_9]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_9,
  [ROUTES.CHAPTER_1_SCENE_10]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_10,
  [ROUTES.CHAPTER_1_SCENE_11]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_11,
  [ROUTES.CHAPTER_1_SCENE_12]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_12,
  [ROUTES.CHAPTER_1_SCENE_13]: LABELS.SCENES_LIST.CHAPTER_1_SCENE_13,
};
