export const LABELS_CONSTANTS = {
  SCENES_LIST: {
    //CHAPTER 1
    CHAPTER_1: 'Capítulo: Humedal',
    CHAPTER_1_SCENE_1: 'Humedal - Escena 1',
    CHAPTER_1_SCENE_2: 'Humedal - Escena 2',
    CHAPTER_1_SCENE_3: 'Humedal - Escena 3',
    CHAPTER_1_SCENE_4: 'Humedal - Escena 4',
    CHAPTER_1_SCENE_5: 'Humedal - Escena 5',
    CHAPTER_1_SCENE_6: 'Humedal - Escena 6',
    CHAPTER_1_SCENE_7: 'Humedal - Escena 7',
    CHAPTER_1_SCENE_8: 'Humedal - Escena 8',
    CHAPTER_1_SCENE_9: 'Humedal - Escena 9',
    CHAPTER_1_SCENE_10: 'Humedal - Escena 10',
    CHAPTER_1_SCENE_11: 'Humedal - Escena 11',
    CHAPTER_1_SCENE_12: 'Humedal - Escena 12',
    CHAPTER_1_SCENE_13: 'Humedal - Escena 13',
    //CHAPTER 2
    CHAPTER_2: 'Capítulo: Bosque',
    CHAPTER_2_SCENE_1: 'Bosque - Escena 1',
    CHAPTER_2_SCENE_2: 'Bosque - Escena 2',
    CHAPTER_2_SCENE_3: 'Bosque - Escena 3',
    CHAPTER_2_SCENE_4: 'Bosque - Escena 4',
    CHAPTER_2_SCENE_5: 'Bosque - Escena 5',
    CHAPTER_2_SCENE_6: 'Bosque - Escena 6',
    //CHAPTER 3
    CHAPTER_3: 'Capítulo: Desierto',
    CHAPTER_3_SCENE_1: 'Desierto - Escena 1',
    CHAPTER_3_SCENE_2: 'Desierto - Escena 2',
    CHAPTER_3_SCENE_3: 'Desierto - Escena 3',
    CHAPTER_3_SCENE_4: 'Desierto - Escena 4',
    CHAPTER_3_SCENE_5: 'Desierto - Escena 5',
    CHAPTER_3_SCENE_6: 'Desierto - Escena 6',
    CHAPTER_3_SCENE_7: 'Desierto - Escena 7',
    CHAPTER_3_SCENE_8: 'Desierto - Escena 8',
    //CHAPTER 4
    CHAPTER_4: 'Capítulo: Llanos',
    CHAPTER_4_SCENE_1: 'Llanos - Escena 1',
    CHAPTER_4_SCENE_2: 'Llanos - Escena 2',
    CHAPTER_4_SCENE_3: 'Llanos - Escena 3',
    CHAPTER_4_SCENE_4: 'Llanos - Escena 4',
    CHAPTER_4_SCENE_5: 'Llanos - Escena 5',
    CHAPTER_4_SCENE_6: 'Llanos - Escena 6',
    //CHAPTER 5
    CHAPTER_5: 'Capítulo: Río',
    CHAPTER_5_SCENE_1: 'Río - Escena 1',
    CHAPTER_5_SCENE_2: 'Río - Escena 2',
    CHAPTER_5_SCENE_3: 'Río - Escena 3',
    CHAPTER_5_SCENE_4: 'Río - Escena 4',
    CHAPTER_5_SCENE_5: 'Río - Escena 5',
    CHAPTER_5_SCENE_6: 'Río - Escena 6',
    CHAPTER_5_SCENE_7: 'Río - Escena 7',
  },
};
