import { IScenesList } from '@app/core/models/scenes-list.model';
import { LABELS_CONSTANTS as LABELS } from '@app/domain/services/labels/labels.constants';
import { APP_ROUTES as ROUTES } from '@app/app.routes';
import { ESCENES_LIST } from '@app/core/enums/scenes-list.enum';

export const SCENES_LIST_CONTENT: IScenesList[] = [
  // CHAPTER 1
  {
    path: ROUTES.CHAPTER_1,
    text: LABELS.SCENES_LIST.CHAPTER_1,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.CHAPTER,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_1,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_1,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_2,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_2,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_3,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_3,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_4,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_4,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_5,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_5,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_6,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_6,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_7,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_7,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_8,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_8,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_9,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_9,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_10,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_10,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_11,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_11,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_12,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_12,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_1_SCENE_13,
    text: LABELS.SCENES_LIST.CHAPTER_1_SCENE_13,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  // CHAPTER 2
  {
    path: ROUTES.CHAPTER_2,
    text: LABELS.SCENES_LIST.CHAPTER_2,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.CHAPTER,
  },
  {
    path: ROUTES.CHAPTER_2_SCENE_1,
    text: LABELS.SCENES_LIST.CHAPTER_2_SCENE_1,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_2_SCENE_2,
    text: LABELS.SCENES_LIST.CHAPTER_2_SCENE_2,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_2_SCENE_3,
    text: LABELS.SCENES_LIST.CHAPTER_2_SCENE_3,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_2_SCENE_4,
    text: LABELS.SCENES_LIST.CHAPTER_2_SCENE_4,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_2_SCENE_5,
    text: LABELS.SCENES_LIST.CHAPTER_2_SCENE_5,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_2_SCENE_6,
    text: LABELS.SCENES_LIST.CHAPTER_2_SCENE_6,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  // CHAPTER 3
  {
    path: ROUTES.CHAPTER_3,
    text: LABELS.SCENES_LIST.CHAPTER_3,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.CHAPTER,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_1,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_1,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_2,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_2,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_3,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_3,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_4,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_4,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_5,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_5,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_6,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_6,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_7,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_7,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_3_SCENE_8,
    text: LABELS.SCENES_LIST.CHAPTER_3_SCENE_8,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  // CHAPTER 4
  {
    path: ROUTES.CHAPTER_4,
    text: LABELS.SCENES_LIST.CHAPTER_4,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.CHAPTER,
  },
  {
    path: ROUTES.CHAPTER_4_SCENE_1,
    text: LABELS.SCENES_LIST.CHAPTER_4_SCENE_1,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_4_SCENE_2,
    text: LABELS.SCENES_LIST.CHAPTER_4_SCENE_2,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_4_SCENE_3,
    text: LABELS.SCENES_LIST.CHAPTER_4_SCENE_3,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_4_SCENE_4,
    text: LABELS.SCENES_LIST.CHAPTER_4_SCENE_4,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_4_SCENE_5,
    text: LABELS.SCENES_LIST.CHAPTER_4_SCENE_5,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_4_SCENE_6,
    text: LABELS.SCENES_LIST.CHAPTER_4_SCENE_6,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  // CHAPTER 5
  {
    path: ROUTES.CHAPTER_5,
    text: LABELS.SCENES_LIST.CHAPTER_5,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.CHAPTER,
  },
  {
    path: ROUTES.CHAPTER_5_SCENE_1,
    text: LABELS.SCENES_LIST.CHAPTER_5_SCENE_1,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_5_SCENE_2,
    text: LABELS.SCENES_LIST.CHAPTER_5_SCENE_2,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_5_SCENE_3,
    text: LABELS.SCENES_LIST.CHAPTER_5_SCENE_3,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_5_SCENE_4,
    text: LABELS.SCENES_LIST.CHAPTER_5_SCENE_4,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_5_SCENE_5,
    text: LABELS.SCENES_LIST.CHAPTER_5_SCENE_5,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_5_SCENE_6,
    text: LABELS.SCENES_LIST.CHAPTER_5_SCENE_6,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
  {
    path: ROUTES.CHAPTER_5_SCENE_7,
    text: LABELS.SCENES_LIST.CHAPTER_5_SCENE_7,
    iconUrl: 'https://elcaminodelatortuga.com/assets/icons/arrow-right.png',
    iconAlt: 'Flecha derecha',
    type: ESCENES_LIST.SCENE,
  },
];
